import { ownGitChangeProposal } from "./git-change-contract.js";
import type {
  GitChangeProposal,
  GitChangeProposalV2,
} from "./git-change-proposal.js";
import {
  stageGitChangeForPromotion,
  type StagedGitChangeV1,
} from "./git-change-stage.js";
import type { Digest } from "./types.js";

const ATTEMPT_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;
const MAX_PATCH_BYTES = 4 * 1024 * 1024;

export interface PreparedGitPromotionObjectsV1 {
  preparedVersion: 1;
  attemptId: string;
  proposalId: Digest;
  expectedOldOid: string;
  baseCommit: string;
  candidateCommitOid: string;
  candidateTreeOid: string;
  staged: StagedGitChangeV1;
  effectDigest: Digest;
  /** Digest of the exact host-generated raw commit bytes, not caller metadata. */
  hostCommitMetadataDigest: Digest;
  createdAt: string;
}

export interface PrepareGitPromotionObjectsInput {
  proposal: GitChangeProposalV2;
  repositoryPath: string;
  patch: Uint8Array;
  /** Fresh UUIDv4 generated by the trusted host for this attempt. */
  attemptId: string;
}

/**
 * Host-only object preparation. NOT authorization, approval consumption, or
 * promotion. May leave unreachable objects, even on failure. No ref writes.
 */
export function prepareGitPromotionObjects(
  input: PrepareGitPromotionObjectsInput,
): PreparedGitPromotionObjectsV1 {
  // Read caller fields once; copy bytes before traversing proposal accessors.
  const {
    proposal: proposalInput,
    repositoryPath,
    patch: patchInput,
    attemptId,
  } = input;
  if (
    typeof repositoryPath !== "string" ||
    typeof attemptId !== "string" ||
    !ATTEMPT_PATTERN.test(attemptId)
  ) {
    throw new Error(
      "Object preparation requires a repository path and canonical lowercase attempt UUIDv4",
    );
  }
  if (
    !(patchInput instanceof Uint8Array) ||
    patchInput.byteLength === 0 ||
    patchInput.byteLength > MAX_PATCH_BYTES
  ) {
    throw new Error("Patch bytes do not match the bounded proposal patch");
  }
  const patch = Buffer.from(patchInput);
  const proposal = ownGitChangeProposal(proposalInput as GitChangeProposal);
  if (proposal.proposalVersion !== 2)
    throw new Error("Object preparation requires a V2 proposal");
  return stageGitChangeForPromotion(proposal, repositoryPath, patch, attemptId);
}
